/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { InfoContract } from "./InfoContract";
export type { MetaCoin } from "./MetaCoin";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { InfoContract__factory } from "./factories/InfoContract__factory";
export { MetaCoin__factory } from "./factories/MetaCoin__factory";
